version: "3"

services:
  springboot-app:
    container_name: spring-app
    image: todoapp
    build: .
    ports:
      - 8080:8080
    environment:
      MYSQL_HOST: mysqldb
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_PORT: 3306
    depends_on:
      - mysqldb
    networks:
      - todoapp-network

  mysqldb:
    container_name: mysqldb
    image: mysql
    volumes:
      -  database:/var/lib/mysql
    ports:
      - 3307:3306
    environment:
      MYSQL_DATABASE: todoapp
      MYSQL_ROOT_PASSWORD: root
    networks:
      - todoapp-network

volumes:
  database:

networks:
  todoapp-network: